# Generated by Django 3.2.6 on 2022-08-03 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rank', models.IntegerField(default=0)),
                ('FILM', models.CharField(default='', max_length=100, null=True)),
                ('Genre', models.CharField(default='', max_length=100, null=True)),
                ('Sub_Genre_1', models.CharField(default='', max_length=100, null=True)),
                ('Sub_Genre_2', models.CharField(default='', max_length=100, null=True)),
                ('Rating', models.CharField(default='', max_length=100, null=True)),
                ('Year_of_Release', models.CharField(default='', max_length=100, null=True)),
                ('Country', models.CharField(default='', max_length=100, null=True)),
                ('Run_Time', models.CharField(default='', max_length=100, null=True)),
                ('Franchise', models.CharField(default='', max_length=100, null=True)),
                ('Synopsis', models.CharField(default='', max_length=100, null=True)),
                ('Keywords_1', models.CharField(default='', max_length=100, null=True)),
                ('Keywords_2', models.CharField(default='', max_length=100, null=True)),
                ('Keywords_3', models.CharField(default='', max_length=100, null=True)),
                ('Keywords_4', models.CharField(default='', max_length=100, null=True)),
                ('Production_Method', models.CharField(default='', max_length=100, null=True)),
                ('Creative_Type', models.CharField(default='', max_length=100, null=True)),
                ('Production_Companies', models.CharField(default='', max_length=100, null=True)),
                ('Production_Company_1', models.CharField(default='', max_length=100, null=True)),
                ('Production_Company_2', models.CharField(default='', max_length=100, null=True)),
                ('Production_Company_3', models.CharField(default='', max_length=100, null=True)),
                ('Production_Company_4', models.CharField(default='', max_length=100, null=True)),
                ('Director', models.CharField(default='', max_length=100, null=True)),
                ('Lead_Actor_1_Name', models.CharField(default='', max_length=100, null=True)),
                ('Lead_Actor_1_Gender', models.CharField(default='', max_length=100, null=True)),
                ('Lead_Actor_1_Age', models.CharField(default='', max_length=100, null=True)),
                ('Lead_Actor_1_Nationality', models.CharField(default='', max_length=100, null=True)),
                ('Lead_Actor_2_Name', models.CharField(default='', max_length=100, null=True)),
                ('Lead_Actor_2_Gender', models.CharField(default='', max_length=100, null=True)),
                ('Lead_Actor_2_Age', models.CharField(default='', max_length=100, null=True)),
                ('Lead_Actor_2_Nationality', models.CharField(default='', max_length=100, null=True)),
                ('Target_Audience', models.CharField(default='', max_length=100, null=True)),
                ('Streamer', models.CharField(default='', max_length=100, null=True)),
                ('Awards_1', models.CharField(default='', max_length=100, null=True)),
                ('Awards_2', models.CharField(default='', max_length=100, null=True)),
                ('Awards_3', models.CharField(default='', max_length=100, null=True)),
                ('Type_of_Deal', models.CharField(default='', max_length=100, null=True)),
                ('RELEASE_DATE', models.CharField(default='', max_length=100, null=True)),
                ('DIST', models.CharField(default='', max_length=100, null=True)),
                ('NO_Screens', models.CharField(default='', max_length=100, null=True)),
                ('Opening_Day_Amd', models.CharField(default='', max_length=100, null=True)),
                ('First_Weekend_BO', models.CharField(default='', max_length=100, null=True)),
                ('First_Weekend_Amd', models.CharField(default='', max_length=100, null=True)),
                ('First_Week_BO', models.CharField(default='', max_length=100, null=True)),
                ('First_Week_ADM', models.CharField(default='', max_length=100, null=True)),
                ('CUM_BO', models.CharField(default='', max_length=100, null=True)),
                ('CUM_ADM', models.CharField(default='', max_length=100, null=True)),
                ('CUM_GBO_USD', models.CharField(default='', max_length=100, null=True)),
            ],
        ),
    ]
