# Generated by Django 3.2.6 on 2022-08-06 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20220805_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='NO_Screens',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='RELEASE_DATE',
            field=models.DateField(null=True),
        ),
    ]
