# Generated by Django 3.2.6 on 2022-08-07 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_data_film'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='FILM',
            field=models.CharField(default='D', max_length=5000, unique=True),
            preserve_default=False,
        ),
    ]
