# Generated by Django 3.2.6 on 2022-08-07 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_data_film'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='CUM_GBO_USD',
            field=models.FloatField(null=True),
        ),
    ]
