# Generated by Django 3.2.6 on 2022-08-09 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20220809_2121'),
    ]

    operations = [
        migrations.CreateModel(
            name='ksa_tv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Count_Order', models.IntegerField(null=True)),
                ('Prog_Name', models.CharField(max_length=5000, unique=True)),
                ('Station', models.CharField(max_length=5000, null=True)),
                ('Dow', models.CharField(max_length=5000, null=True)),
                ('Month_Year', models.DateField(null=True)),
                ('Prog_Sub_Type', models.CharField(max_length=5000, null=True)),
                ('Prog_Type', models.CharField(max_length=5000, null=True)),
                ('Prog_Domain', models.CharField(max_length=5000, null=True)),
                ('first_Actor', models.CharField(max_length=5000, null=True)),
                ('second_Actor', models.CharField(max_length=5000, null=True)),
                ('Prog_Producer', models.CharField(max_length=5000, null=True)),
                ('Prog_Distributor', models.CharField(max_length=5000, null=True)),
                ('Survey_From', models.TimeField(null=True)),
                ('Survey_To', models.TimeField(null=True)),
                ('Avg_Aud_ALL', models.FloatField(null=True)),
            ],
        ),
    ]
