# Generated by Django 3.2.6 on 2022-08-09 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_ksa_tv'),
    ]

    operations = [
        migrations.CreateModel(
            name='global_box',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rank', models.IntegerField(null=True)),
                ('Movie', models.CharField(max_length=5000, unique=True)),
                ('Release_Year', models.DateField(null=True)),
                ('Genre', models.CharField(max_length=5000, null=True)),
                ('Sub_Genera_1', models.CharField(max_length=5000, null=True)),
                ('Sub_Genera_2', models.CharField(max_length=5000, null=True)),
                ('Production_Budget', models.IntegerField(null=True)),
                ('Other_Costs', models.IntegerField(null=True)),
                ('Profit', models.IntegerField(null=True)),
                ('Profitability', models.IntegerField(null=True)),
                ('Rating', models.FloatField(null=True)),
                ('Run_Time', models.TimeField(null=True)),
                ('Franchise', models.CharField(max_length=5000, null=True)),
                ('Key_Word_1', models.CharField(max_length=5000, null=True)),
                ('Key_Word_2', models.CharField(max_length=5000, null=True)),
                ('Key_Word_3', models.CharField(max_length=5000, null=True)),
                ('Key_Word_4', models.CharField(max_length=5000, null=True)),
                ('Key_Word_5', models.CharField(max_length=5000, null=True)),
                ('Source', models.CharField(max_length=5000, null=True)),
                ('Production_Method', models.CharField(max_length=5000, null=True)),
                ('Creative_Type', models.CharField(max_length=5000, null=True)),
                ('Prod_Companies', models.CharField(max_length=5000, null=True)),
                ('Prod_Company_1', models.CharField(max_length=5000, null=True)),
                ('Prod_Company_2', models.CharField(max_length=5000, null=True)),
                ('Prod_Company_3', models.CharField(max_length=5000, null=True)),
                ('Prod_Company_4', models.CharField(max_length=5000, null=True)),
                ('Production_Country_1', models.CharField(max_length=5000, null=True)),
                ('Production_Country_2', models.CharField(max_length=5000, null=True)),
                ('Production_Country_3', models.CharField(max_length=5000, null=True)),
                ('Language', models.CharField(max_length=5000, null=True)),
                ('Domestic_Box_office', models.IntegerField(null=True)),
                ('International_Box_Office', models.IntegerField(null=True)),
                ('World_Wide_Box_Office', models.IntegerField(null=True)),
            ],
        ),
    ]
