# Generated by Django 3.2.6 on 2022-08-09 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_global_box'),
    ]

    operations = [
        migrations.CreateModel(
            name='prod_companies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Production_Companies', models.CharField(max_length=5000, null=True)),
                ('No_of_Movies', models.CharField(max_length=5000, null=True)),
                ('Total_Domestic_Box_Office', models.CharField(max_length=5000, null=True)),
                ('Total_Worldwide_Box_Office', models.CharField(max_length=5000, null=True)),
            ],
        ),
    ]
