# Generated by Django 3.2.6 on 2022-08-10 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20220810_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='global_box',
            name='Run_Time',
            field=models.CharField(max_length=5000, null=True),
        ),
    ]
