# Generated by Django 3.2.6 on 2022-08-10 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_alter_global_box_run_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='global_box',
            name='Release_Year',
            field=models.DateTimeField(null=True),
        ),
    ]
