# Generated by Django 3.2.6 on 2022-08-10 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_alter_global_box_release_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='global_box',
            name='Release_Year',
            field=models.CharField(max_length=5000, null=True),
        ),
    ]
