# Generated by Django 3.2.6 on 2022-08-10 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_auto_20220810_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ksa_tv',
            name='Month_Year',
            field=models.CharField(max_length=5000, null=True),
        ),
    ]
