# Generated by Django 3.2.6 on 2022-08-10 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_alter_ksa_tv_month_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prod_companies',
            name='No_of_Movies',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='prod_companies',
            name='Production_Companies',
            field=models.CharField(default='-', max_length=5000, unique=True),
        ),
        migrations.AlterField(
            model_name='prod_companies',
            name='Total_Domestic_Box_Office',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='prod_companies',
            name='Total_Worldwide_Box_Office',
            field=models.IntegerField(null=True),
        ),
    ]
