# Generated by Django 3.2.6 on 2022-08-10 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_alter_prod_companies_production_companies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prod_companies',
            name='Total_Domestic_Box_Office',
            field=models.CharField(max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='prod_companies',
            name='Total_Worldwide_Box_Office',
            field=models.CharField(max_length=5000, null=True),
        ),
    ]
