# Generated by Django 3.2.6 on 2022-08-10 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_auto_20220810_2341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='global_box',
            name='Domestic_Box_office',
            field=models.CharField(max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='global_box',
            name='International_Box_Office',
            field=models.CharField(max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='global_box',
            name='Other_Costs',
            field=models.CharField(max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='global_box',
            name='Production_Budget',
            field=models.CharField(max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='global_box',
            name='Profit',
            field=models.CharField(max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='global_box',
            name='World_Wide_Box_Office',
            field=models.CharField(max_length=5000, null=True),
        ),
    ]
