# Generated by Django 3.2.6 on 2022-09-03 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_netflix_series'),
    ]

    operations = [
        migrations.CreateModel(
            name='netflix_Movies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Year', models.CharField(max_length=5000, null=True)),
                ('Week', models.CharField(max_length=5000, null=True)),
                ('Name', models.CharField(max_length=5000, unique=True)),
                ('Points', models.CharField(max_length=5000, null=True)),
                ('Rank', models.CharField(max_length=5000, null=True)),
                ('Genre', models.CharField(max_length=5000, null=True)),
                ('Sub_Genre_1', models.CharField(max_length=5000, null=True)),
                ('Sub_Genre_2', models.CharField(max_length=5000, null=True)),
                ('Rating', models.CharField(max_length=5000, null=True)),
                ('Year_of_Release', models.CharField(max_length=5000, null=True)),
                ('Country', models.CharField(max_length=5000, null=True)),
                ('Run_Time', models.CharField(max_length=5000, null=True)),
                ('Franchise', models.CharField(max_length=5000, null=True)),
                ('Synopsis', models.CharField(max_length=5000, null=True)),
                ('Keywords_1', models.CharField(max_length=5000, null=True)),
                ('Keywords_2', models.CharField(max_length=5000, null=True)),
                ('Keywords_3', models.CharField(max_length=5000, null=True)),
                ('Keywords_4', models.CharField(max_length=5000, null=True)),
                ('Production_Method', models.CharField(max_length=5000, null=True)),
                ('Creative_Type', models.CharField(max_length=5000, null=True)),
                ('Production_Companies', models.CharField(max_length=5000, null=True)),
                ('Production_Company_1', models.CharField(max_length=5000, null=True)),
                ('Production_Company_2', models.CharField(max_length=5000, null=True)),
                ('Production_Company_3', models.CharField(max_length=5000, null=True)),
                ('Production_Company_4', models.CharField(max_length=5000, null=True)),
                ('Directed_by', models.CharField(max_length=5000, null=True)),
                ('Lead_Actor_1_Name', models.CharField(max_length=5000, null=True)),
                ('Lead_Actor_1_Gender', models.CharField(max_length=5000, null=True)),
                ('Lead_Actor_1_Age', models.CharField(max_length=5000, null=True)),
                ('Lead_Actor_1_Nationality', models.CharField(max_length=5000, null=True)),
                ('Lead_Actor_2_Name', models.CharField(max_length=5000, null=True)),
                ('Lead_Actor_2_Gender', models.CharField(max_length=5000, null=True)),
                ('Lead_Actor_2_Age', models.CharField(max_length=5000, null=True)),
                ('Lead_Actor_2_Nationality', models.CharField(max_length=5000, null=True)),
                ('Target_Audience', models.CharField(max_length=5000, null=True)),
                ('Streamer', models.CharField(max_length=5000, null=True)),
                ('Awards_1', models.CharField(max_length=5000, null=True)),
                ('Awards_2', models.CharField(max_length=5000, null=True)),
                ('Awards_3', models.CharField(max_length=5000, null=True)),
            ],
        ),
    ]
