# Generated by Django 3.2.6 on 2022-09-03 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_netflix_movies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='netflix_movies',
            name='Points',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='netflix_series',
            name='Points',
            field=models.IntegerField(null=True),
        ),
    ]
