# Generated by Django 3.2.6 on 2022-09-27 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_auto_20220903_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='global_box',
            name='Domestic_Box_office',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='global_box',
            name='International_Box_Office',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='global_box',
            name='World_Wide_Box_Office',
            field=models.FloatField(null=True),
        ),
    ]
