# Generated by Django 3.2.6 on 2022-09-27 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_auto_20220927_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='global_box',
            name='Production_Budget',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='global_box',
            name='Profit',
            field=models.FloatField(null=True),
        ),
    ]
