# Generated by Django 3.2.6 on 2022-09-27 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_alter_global_box_other_costs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='netflix_movies',
            name='Rating',
            field=models.FloatField(null=True),
        ),
    ]
