# -*- encoding: utf-8 -*-
"""
Copyright (c) 2019 - present AppSeed.us
"""

from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class data(models.Model):
    Rank=models.IntegerField(default=0)
    FILM=models.CharField(max_length=5000,unique=True)
    Genre=models.CharField(null=True,max_length=5000)
    Sub_Genre_1=models.CharField(null=True,max_length=5000)
    Sub_Genre_2=models.CharField(null=True,max_length=5000)
    Rating=models.CharField(null=True,max_length=5000)
    Year_of_Release =models.CharField(null=True,max_length=5000)
    Country =models.CharField(null=True,max_length=5000)
    Run_Time=models.CharField(null=True,max_length=5000)
    Franchise=models.CharField(null=True,max_length=5000)
    Synopsis =models.CharField(null=True,max_length=5000)
    Keywords_1=models.CharField(null=True,max_length=5000)
    Keywords_2=models.CharField(null=True,max_length=5000)
    Keywords_3=models.CharField(null=True,max_length=5000)
    Keywords_4=models.CharField(null=True,max_length=5000)
    Production_Method =models.CharField(null=True,max_length=5000)
    Creative_Type =models.CharField(null=True,max_length=5000)
    Production_Companies=models.CharField(null=True,max_length=5000)
    Production_Company_1=models.CharField(null=True,max_length=5000)
    Production_Company_2=models.CharField(null=True,max_length=5000)
    Production_Company_3=models.CharField(null=True,max_length=5000)
    Production_Company_4=models.CharField(null=True,max_length=5000)
    Director=models.CharField(null=True,max_length=5000)
    Lead_Actor_1_Name =models.CharField(null=True,max_length=5000)
    Lead_Actor_1_Gender=models.CharField(null=True,max_length=5000)
    Lead_Actor_1_Age =models.CharField(null=True,max_length=5000)
    Lead_Actor_1_Nationality=models.CharField(null=True,max_length=5000)
    Lead_Actor_2_Name =models.CharField(null=True,max_length=5000)
    Lead_Actor_2_Gender=models.CharField(null=True,max_length=5000)
    Lead_Actor_2_Age =models.CharField(null=True,max_length=5000)
    Lead_Actor_2_Nationality=models.CharField(null=True,max_length=5000)
    Target_Audience =models.CharField(null=True,max_length=5000)
    Streamer =models.CharField(null=True,max_length=5000)
    Awards_1  =models.CharField(null=True,max_length=5000)
    Awards_2  =models.CharField(null=True,max_length=5000)
    Awards_3  =models.CharField(null=True,max_length=5000)
    Type_of_Deal =models.CharField(null=True,max_length=5000)
    RELEASE_DATE  =models.DateField(null=True)
    DIST  =models.CharField(null=True,max_length=5000)
    NO_Screens  =models.IntegerField(null=True)
    Opening_Day_Amd  =models.IntegerField(null=True)
    First_Weekend_BO  =models.IntegerField(null=True)
    First_Weekend_Amd  =models.IntegerField(null=True)
    First_Week_BO  =models.IntegerField(null=True)
    First_Week_ADM  =models.IntegerField(null=True)
    CUM_BO  =models.IntegerField(null=True)
    CUM_ADM  =models.IntegerField(null=True)
    CUM_GBO_USD =models.FloatField(null=True)


class ksa_tv(models.Model):
    Count_Order=models.IntegerField(null=True)
    Prog_Name=models.CharField(max_length=5000,unique=True)
    Station=models.CharField(max_length=5000,null=True)
    Dow=models.CharField(max_length=5000,null=True)
    Month_Year=models.CharField(max_length=5000,null=True)
    Prog_Sub_Type=models.CharField(max_length=5000,null=True)
    Prog_Type=models.CharField(max_length=5000,null=True)
    Prog_Domain=models.CharField(max_length=5000,null=True)
    first_Actor=models.CharField(max_length=5000,null=True)
    second_Actor=models.CharField(max_length=5000,null=True)
    Prog_Producer=models.CharField(max_length=5000,null=True)
    Prog_Distributor=models.CharField(max_length=5000,null=True)
    Survey_From=models.CharField(max_length=5000, null=True)
    Survey_To=models.CharField(max_length=5000, null=True)
    Avg_Aud_ALL=models.FloatField(null=True)



class global_box(models.Model):
    Rank=models.IntegerField(null=True)
    Movie =models.CharField(max_length=5000,unique=True)
    Release_Year =models.CharField(max_length=5000,null=True)
    Genre=models.CharField(max_length=5000,null=True)
    Sub_Genera_1=models.CharField(max_length=5000,null=True)
    Sub_Genera_2=models.CharField(max_length=5000,null=True)
    Production_Budget =models.FloatField(null=True)
    Other_Costs =models.FloatField(null=True)
    Profit  =models.FloatField(null=True)
    Profitability =models.IntegerField(null=True)
    Rating =models.CharField(max_length=5000,null=True)
    Run_Time =models.CharField(max_length=5000,null=True)
    Franchise =models.CharField(max_length=5000,null=True)
    Key_Word_1 =models.CharField(max_length=5000,null=True)
    Key_Word_2=models.CharField(max_length=5000,null=True)
    Key_Word_3=models.CharField(max_length=5000,null=True)
    Key_Word_4=models.CharField(max_length=5000,null=True)
    Key_Word_5=models.CharField(max_length=5000,null=True)
    Source =models.CharField(max_length=5000,null=True)
    Production_Method =models.CharField(max_length=5000,null=True)
    Creative_Type =models.CharField(max_length=5000,null=True)
    Prod_Companies =models.CharField(max_length=5000,null=True)
    Prod_Company_1 =models.CharField(max_length=5000,null=True)
    Prod_Company_2=models.CharField(max_length=5000,null=True)
    Prod_Company_3=models.CharField(max_length=5000,null=True)
    Prod_Company_4=models.CharField(max_length=5000,null=True)
    Production_Country_1 =models.CharField(max_length=5000,null=True)
    Production_Country_2=models.CharField(max_length=5000,null=True)
    Production_Country_3=models.CharField(max_length=5000,null=True)
    Language =models.CharField(max_length=5000,null=True)
    Domestic_Box_office =models.FloatField(null=True)
    International_Box_Office =models.FloatField(null=True)
    World_Wide_Box_Office =models.FloatField(null=True)



class prod_companies(models.Model):

    Production_Companies=models.CharField(max_length=5000,unique=True)
    No_of_Movies=models.IntegerField(null=True)
    Total_Domestic_Box_Office=models.FloatField(null=True)
    Total_Worldwide_Box_Office=models.FloatField(null=True)


class series(models.Model):
    Series_Name=models.CharField(max_length=5000,unique=True)
    Genre =models.CharField(null=True,max_length=5000)
    Sub_Genre_1 =models.CharField(null=True,max_length=5000)
    Sub_Genre_2 =models.CharField(null=True,max_length=5000)
    Rating =models.FloatField(null=True)
    Year_of_Release =models.CharField(null=True,max_length=5000)
    Country =models.CharField(null=True,max_length=5000)
    Seasons =models.IntegerField(null=True)
    Episodes_Season =models.IntegerField(null=True)
    Length_of_Episodes =models.CharField(null=True,max_length=5000)
    Synopsis =models.CharField(null=True,max_length=5000)
    Keywords_1 =models.CharField(null=True,max_length=5000)
    Keywords_2 =models.CharField(null=True,max_length=5000)
    Keywords_3=models.CharField(null=True,max_length=5000)
    Keywords_4=models.CharField(null=True,max_length=5000)
    Production_Method =models.CharField(null=True,max_length=5000)
    Creative_Type =models.CharField(null=True,max_length=5000)
    Production_Companies =models.IntegerField(null=True)
    Production_Company_1 =models.CharField(null=True,max_length=5000)
    Production_Company_2=models.CharField(null=True,max_length=5000)
    Production_Company_3=models.CharField(null=True,max_length=5000)
    Production_Company_4=models.CharField(null=True,max_length=5000)
    Director=models.CharField(null=True,max_length=5000)
    Lead_Actor_1_Name =models.CharField(null=True,max_length=5000)
    Lead_Actor_1_Gender=models.CharField(null=True,max_length=5000)
    Lead_Actor_1_Age =models.IntegerField(null=True)
    Lead_Actor_1_Nationality=models.CharField(null=True,max_length=5000)
    Lead_Actor_2_Name =models.CharField(null=True,max_length=5000)
    Lead_Actor_2_Gender=models.CharField(null=True,max_length=5000)
    Lead_Actor_2_Age =models.IntegerField(null=True)
    Lead_Actor_2_Nationality=models.CharField(null=True,max_length=5000)
    Target_Audience =models.CharField(null=True,max_length=5000)
    Streamer=models.CharField(null=True,max_length=5000)
    Awards_1 =models.CharField(null=True,max_length=5000)
    Awards_2=models.CharField(null=True,max_length=5000)
    Awards_3 =models.CharField(null=True,max_length=5000)
    Type_of_deal=models.CharField(null=True,max_length=5000)


class netflix_series(models.Model):
   
    Year=models.CharField(max_length=5000,null=True)
    Week=models.CharField(max_length=5000,null=True)
    Name =models.CharField(max_length=5000,unique=True)
    Points =models.IntegerField(null=True)
    Rank=models.CharField(max_length=5000,null=True)
    Genre =models.CharField(max_length=5000,null=True)
    Sub_Genre_1=models.CharField(max_length=5000,null=True)
    Sub_Genre_2=models.CharField(max_length=5000,null=True)
    Rating=models.CharField(max_length=5000,null=True)
    Year_of_Release =models.CharField(max_length=5000,null=True)
    Country =models.CharField(max_length=5000,null=True)
    of_Seasons=models.CharField(max_length=5000,null=True)
    of_episodes_Season=models.CharField(max_length=5000,null=True)
    Length_of_Episode=models.CharField(max_length=5000,null=True)
    Synopsis =models.CharField(max_length=5000,null=True)
    Keywords_1=models.CharField(max_length=5000,null=True)
    Keywords_2=models.CharField(max_length=5000,null=True)
    Keywords_3=models.CharField(max_length=5000,null=True)
    Keywords_4=models.CharField(max_length=5000,null=True)
    Production_Method =models.CharField(max_length=5000,null=True)
    Creative_Type =models.CharField(max_length=5000,null=True)
    Production_Companies=models.CharField(max_length=5000,null=True)
    Production_Company_1=models.CharField(max_length=5000,null=True)
    Production_Company_2=models.CharField(max_length=5000,null=True)
    Production_Company_3=models.CharField(max_length=5000,null=True)
    Production_Company_4=models.CharField(max_length=5000,null=True)
    Directed_by=models.CharField(max_length=5000,null=True)
    Lead_Actor_1_Name =models.CharField(max_length=5000,null=True)
    Lead_Actor_1_Gender=models.CharField(max_length=5000,null=True)
    Lead_Actor_1_Age =models.CharField(max_length=5000,null=True)
    Lead_Actor_1_Nationality=models.CharField(max_length=5000,null=True)
    Lead_Actor_2_Name =models.CharField(max_length=5000,null=True)
    Lead_Actor_2_Gender=models.CharField(max_length=5000,null=True)
    Lead_Actor_2_Age =models.CharField(max_length=5000,null=True)
    Lead_Actor_2_Nationality=models.CharField(max_length=5000,null=True)
    Target_Audience =models.CharField(max_length=5000,null=True)
    Streamer=models.CharField(max_length=5000,null=True)
    Awards_1=models.CharField(max_length=5000,null=True)
    Awards_2 =models.CharField(max_length=5000,null=True)
    Awards_3 =models.CharField(max_length=5000,null=True)


    def __str__(self):
        return self.Name




class netflix_Movies(models.Model):
   
    Year=models.CharField(max_length=5000,null=True)
    Week=models.CharField(max_length=5000,null=True)
    Name =models.CharField(max_length=5000,unique=True)
    Points =models.IntegerField(null=True)
    Rank=models.CharField(max_length=5000,null=True)
    Genre =models.CharField(max_length=5000,null=True)
    Sub_Genre_1=models.CharField(max_length=5000,null=True)
    Sub_Genre_2=models.CharField(max_length=5000,null=True)
    Rating=models.FloatField(null=True)
    Year_of_Release =models.CharField(max_length=5000,null=True)
    Country =models.CharField(max_length=5000,null=True)
    Run_Time=models.CharField(max_length=5000,null=True)
    Franchise=models.CharField(max_length=5000,null=True)
    Synopsis =models.CharField(max_length=5000,null=True)
    Keywords_1=models.CharField(max_length=5000,null=True)
    Keywords_2=models.CharField(max_length=5000,null=True)
    Keywords_3=models.CharField(max_length=5000,null=True)
    Keywords_4=models.CharField(max_length=5000,null=True)
    Production_Method =models.CharField(max_length=5000,null=True)
    Creative_Type =models.CharField(max_length=5000,null=True)
    Production_Companies=models.CharField(max_length=5000,null=True)
    Production_Company_1=models.CharField(max_length=5000,null=True)
    Production_Company_2=models.CharField(max_length=5000,null=True)
    Production_Company_3=models.CharField(max_length=5000,null=True)
    Production_Company_4=models.CharField(max_length=5000,null=True)
    Directed_by=models.CharField(max_length=5000,null=True)
    Lead_Actor_1_Name =models.CharField(max_length=5000,null=True)
    Lead_Actor_1_Gender=models.CharField(max_length=5000,null=True)
    Lead_Actor_1_Age =models.CharField(max_length=5000,null=True)
    Lead_Actor_1_Nationality=models.CharField(max_length=5000,null=True)
    Lead_Actor_2_Name =models.CharField(max_length=5000,null=True)
    Lead_Actor_2_Gender=models.CharField(max_length=5000,null=True)
    Lead_Actor_2_Age =models.CharField(max_length=5000,null=True)
    Lead_Actor_2_Nationality=models.CharField(max_length=5000,null=True)
    Target_Audience =models.CharField(max_length=5000,null=True)
    Streamer=models.CharField(max_length=5000,null=True)
    Awards_1=models.CharField(max_length=5000,null=True)
    Awards_2 =models.CharField(max_length=5000,null=True)
    Awards_3 =models.CharField(max_length=5000,null=True)
    


    def __str__(self):
        return self.Name